(function(){
  const A=window.SaeedAPI,U=window.SaeedUI||{esc:(v='')=>String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))},$=(s,r=document)=>r.querySelector(s),login=$('#portalLogin'),result=$('#portalResult');
  if(!login)return;
  const statusMap={new:'جديد',contacted:'تم التواصل',reserved:'تم الحجز',confirmed:'مؤكد',waiting:'قائمة انتظار',cancelled:'ملغي'},att={present:'حاضر',absent:'غائب',excused:'اعتذار',unmarked:'غير مسجل'},enrollStatus={active:'نشط',waiting:'قائمة انتظار',ended:'سابق',cancelled:'ملغي'};
  function error(host,msg){host.querySelector('.errorBanner')?.remove();host.insertAdjacentHTML('afterbegin',`<div class="errorBanner show">${U.esc(msg)}</div>`)}
  const money=v=>`${Number(v||0).toLocaleString('ar-EG')} ج.م`;
  const date=v=>v?new Date(v).toLocaleDateString('ar-EG'):'—';
  async function load(){try{const d=await A.get('/api/portal/me');render(d);login.classList.add('hidden');setTimeout(()=>A.post('/api/portal/messages/read',{}).catch(()=>{}),1800)}catch(e){if(e.status!==401)error(login,e.message)}}
  login.onsubmit=async e=>{e.preventDefault();const tracking=login.elements.trackingCode.value.trim().toUpperCase(),phone=login.elements.parentPhone.value.trim();try{await A.post('/api/portal/login',{tracking_code:tracking,parent_phone:phone});await load()}catch(e){error(login,e.message)}};
  function enrollmentCard(e){return `<article class="portalSubject ${e.status!=='active'?'portalSubject--muted':''}"><div class="portalSubject__top"><div><span class="statusPill">${U.esc(enrollStatus[e.status]||e.status)}</span><h3>${U.esc(e.subject_text||'مادة')}</h3></div><strong>${U.esc(e.group_code||'بدون مجموعة')}</strong></div><div class="reviewBox"><div class="reviewRow"><span>المدرس</span><strong>${U.esc(e.teacher_name||'يحدد من الإدارة')}</strong></div><div class="reviewRow"><span>المجموعة</span><strong>${U.esc(e.group_code||'—')}</strong></div><div class="reviewRow"><span>المواعيد</span><strong>${U.esc([e.days,e.time].filter(Boolean).join(' • ')||'—')}</strong></div><div class="reviewRow"><span>القاعة</span><strong>${U.esc(e.room||'—')}</strong></div></div>${e.status==='waiting'?`<p class="formNotice">ترتيب قائمة الانتظار: ${Number(e.waitlist_position||0)||'—'}</p>`:''}</article>`}
  function render(d){
    const r=d.registration,paid=d.payments.reduce((s,p)=>s+Number(p.amount||0),0),required=d.subscriptions.reduce((s,x)=>s+Math.max(0,Number(x.amount||0)-Number(x.discount||0)),0),balance=Math.max(0,required-paid),a=d.attendanceSummary||{};
    const active=d.activeEnrollments||[],history=(d.enrollments||[]).filter(x=>!['active','waiting'].includes(x.status));
    result.innerHTML=`<div class="portalDashboard">
      <div class="portalHead"><div><div class="section__kicker">رقم المتابعة: ${U.esc(r.tracking_code||'—')}</div><h2>مرحبًا ${U.esc(r.student_name)}</h2><p>${U.esc(r.stage_name)} • ${U.esc(r.grade_name)} • ولي الأمر: ${U.esc(r.parent_name)}</p></div><button id="portalLogout" class="btn btn--ghost">خروج</button></div>
      <div class="adminStats"><div class="adminStat"><span>المواد الحالية</span><strong>${d.subjectCount||0}</strong></div><div class="adminStat"><span>الحضور</span><strong>${a.present||0}</strong></div><div class="adminStat adminStat--danger"><span>الغياب</span><strong>${a.absent||0}</strong></div><div class="adminStat"><span>اعتذار</span><strong>${a.excused||0}</strong></div><div class="adminStat"><span>المدفوع</span><strong>${money(paid)}</strong></div><div class="adminStat"><span>المتبقي</span><strong>${money(balance)}</strong></div></div>
      <section class="adminCard"><div class="adminCard__head"><div><h2>المواد والمجموعات الحالية</h2><small class="muted">${active.length} مادة/اشتراك نشط أو في الانتظار</small></div></div><div class="portalSubjects">${active.length?active.map(enrollmentCard).join(''):'<p class="muted">لا توجد مواد نشطة حاليًا.</p>'}</div></section>
      <div class="portalGrid">
        <section class="adminCard"><h3>الامتحانات والدرجات</h3>${gradeTable(d.grades)}</section>
        <section class="adminCard"><h3>الحضور والغياب</h3><div class="attendanceMini"><span>إجمالي مسجل: <b>${a.total||0}</b></span><span>حاضر: <b>${a.present||0}</b></span><span>غائب: <b>${a.absent||0}</b></span><span>بعذر: <b>${a.excused||0}</b></span></div>${table(['التاريخ','المادة','الحالة','ملاحظة'],d.attendance.map(x=>[x.session_date,x.subject_text||x.group_code||'—',att[x.status]||x.status,x.note||'—']))}</section>
        <section class="adminCard"><h3>الحسابات المالية</h3><div class="financeSummary"><div><span>إجمالي المطلوب</span><strong>${money(required)}</strong></div><div><span>إجمالي المدفوع</span><strong>${money(paid)}</strong></div><div><span>المتبقي</span><strong>${money(balance)}</strong></div><div><span>الحالة</span><strong>${balance>0?'عليه مبلغ متبقٍ':'لا توجد متأخرات'}</strong></div></div>${table(['الفترة','المطلوب','المدفوع','المتبقي'],d.subscriptions.map(x=>[x.period,money(Number(x.amount)-Number(x.discount||0)),money(x.paid),money(x.balance)]))}</section>
        <section class="adminCard"><h3>سجل الدفعات والإيصالات</h3>${d.payments.length?`<div class="tableWrap"><table class="dataTable"><thead><tr><th>التاريخ</th><th>المبلغ</th><th>الطريقة</th><th>الإيصال</th></tr></thead><tbody>${d.payments.map(p=>`<tr><td>${U.esc(p.paid_at)}</td><td>${money(p.amount)}</td><td>${U.esc(p.method)}</td><td><a class="link" target="_blank" href="${A.authUrl(`/api/portal/receipt/${p.id}`)}">${U.esc(p.receipt_no)}</a></td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">لا توجد دفعات مسجلة.</p>'}</section>
        <section class="adminCard"><div class="adminCard__head"><h3>رسائل السنتر</h3>${d.unreadMessages?`<span class="newBadge">${d.unreadMessages} جديدة</span>`:''}</div>${messageList(d.messages)}</section>
        <section class="adminCard"><h3>ملاحظات المدرس</h3>${d.notes.length?d.notes.map(n=>`<div class="portalNote"><p>${U.esc(n.note)}</p><small>${date(n.created_at)}</small></div>`).join(''):'<p class="muted">لا توجد ملاحظات.</p>'}</section>
        <section class="adminCard"><h3>الملازم والملفات</h3>${d.materials.length?d.materials.map(m=>`<a class="materialLink" href="${U.esc(m.file_url)}" target="_blank">${U.esc(m.title)} <span>تحميل ↗</span></a>`).join(''):'<p class="muted">لا توجد ملفات منشورة.</p>'}</section>
        ${history.length?`<section class="adminCard portalHistory"><h3>السجل القديم للمجموعات والمدرسين</h3>${table(['المادة','المجموعة','المدرس','من','إلى','الحالة'],history.map(e=>[e.subject_text,e.group_code||'—',e.teacher_name||'—',e.start_date||'—',e.end_date||'—',enrollStatus[e.status]||e.status]))}</section>`:''}
      </div></div>`;
    result.classList.remove('hidden');
    $('#portalLogout').onclick=async()=>{await A.post('/api/portal/logout',{});location.reload()};
  }
  function gradeTable(rows){return rows.length?`<div class="examCards">${rows.map(g=>`<article class="examCard"><div class="examCard__score"><strong>${U.esc(g.score??'—')}</strong><span>/ ${U.esc(g.max_score??'—')}</span></div><div class="examCard__body"><h4>${U.esc(g.title)}</h4><p>${U.esc(g.subject_name||g.group_code||'')} ${g.teacher_name?`• ${U.esc(g.teacher_name)}`:''}</p><small>${U.esc(g.exam_date||'—')}</small>${g.note?`<p class="muted">${U.esc(g.note)}</p>`:''}</div>${g.image_url?`<a class="examPaper" href="${U.esc(g.image_url)}" target="_blank"><img src="${U.esc(g.image_url)}" alt="صورة ورقة ${U.esc(g.title)}"><span>فتح ورقة الامتحان</span></a>`:''}</article>`).join('')}</div>`:'<p class="muted">لا توجد درجات مسجلة بعد.</p>'}
  function messageList(rows){return rows.length?rows.map(m=>`<article class="portalMessage ${!m.is_read?'portalMessage--new':''} ${Number(m.priority)>0?'portalMessage--important':''}"><div class="portalMessage__head"><strong>${U.esc(m.title)}</strong><div>${Number(m.priority)>0?'<span class="importantBadge">مهمة</span>':''}${!m.is_read?'<span class="newBadge">جديدة</span>':''}</div></div><p>${U.esc(m.body)}</p><small>${m.group_code?`مجموعة ${U.esc(m.group_code)} • `:''}${date(m.created_at)}</small></article>`).join(''):'<p class="muted">لا توجد رسائل.</p>'}
  function table(h,rows){return rows.length?`<div class="tableWrap"><table class="dataTable"><thead><tr>${h.map(x=>`<th>${U.esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${U.esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<p class="muted">لا توجد بيانات بعد.</p>'}
  load();
})();
