(function(){
  const A=window.SaeedAPI,U=window.SaeedUI||{esc:(v='')=>String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))},$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],form=$('#registrationForm');if(!form)return;
  const pages=$$('.formPage',form),steps=$$('.step'),banner=$('#formError'),stage=$('#stage'),grade=$('#grade'),subject=$('#subject'),teacher=$('#teacher'),group=$('#group');let current=0,last=null,catalog=[],groups=[],teachers=[];const q=new URLSearchParams(location.search),phoneRe=/^01[0125]\d{8}$/;
  const opt=(v,l)=>`<option value="${U.esc(v)}">${U.esc(l)}</option>`;
  function set(el,arr,label){el.innerHTML=opt('',label)+arr.map(x=>opt(x.value,x.label)).join('')}
  function stageObj(){return catalog.find(x=>x.id===Number(stage.value))}function gradeObj(){return stageObj()?.grades.find(x=>x.id===Number(grade.value))}function subjectObj(){return gradeObj()?.subjects.find(x=>x.id===Number(subject.value))}
  function syncGrades(){set(grade,(stageObj()?.grades||[]).map(x=>({value:x.id,label:x.name})),'اختر الصف');syncSubjects()}
  function syncSubjects(){set(subject,(gradeObj()?.subjects||[]).map(x=>({value:x.id,label:x.name})),'اختر المادة');syncPeople()}
  function syncPeople(){const sub=subjectObj()?.name||'',eligible=groups.filter(g=>(!stage.value||g.stage_id===Number(stage.value))&&(!grade.value||g.grade_id===Number(grade.value))&&(!sub||g.subject_text===sub));const tids=[...new Set(eligible.map(g=>g.teacher_id).filter(Boolean))];set(teacher,teachers.filter(t=>!tids.length||tids.includes(t.id)).map(t=>({value:t.id,label:`${t.name}${t.subject_text?' — '+t.subject_text:''}`})),'يُحدد بعد التواصل');set(group,eligible.map(g=>({value:g.id,label:`${g.subject_text} • ${g.teacher_name||'بدون مدرس محدد'} • ${[g.days,g.time].filter(Boolean).join(' ')} • ${g.status==='full'?'قائمة انتظار':`متبقي ${g.remaining}`}`})),'يُحدد بعد التواصل');if(q.get('group')&&eligible.some(x=>x.id===Number(q.get('group'))))group.value=q.get('group')}
  stage.onchange=syncGrades;grade.onchange=syncSubjects;subject.onchange=syncPeople;
  function show(n){current=Math.max(0,Math.min(pages.length-1,n));pages.forEach((p,i)=>p.classList.toggle('active',i===current));steps.forEach((s,i)=>{s.classList.toggle('active',i===current);s.classList.toggle('done',i<current)});banner.classList.remove('show');scrollTo({top:Math.max(0,form.offsetTop-120),behavior:'smooth'})}
  function err(el,msg){el.setAttribute('aria-invalid','true');const e=el.closest('.field')?.querySelector('.field__error');if(e)e.textContent=msg;return false}function clear(p){$$('[aria-invalid="true"]',p).forEach(x=>x.removeAttribute('aria-invalid'));$$('.field__error',p).forEach(x=>x.textContent='')}
  function validate(){const p=pages[current];clear(p);let ok=true;$$('[required]',p).forEach(el=>{if(el.type==='checkbox'&&!el.checked){err(el,'يلزم الموافقة للمتابعة');ok=false}else if(!String(el.value||'').trim()){err(el,'هذا الحقل مطلوب');ok=false}});if(current===2){['studentPhone','parentPhone'].forEach(n=>{const el=form.elements[n];if(el.value&&!phoneRe.test(el.value)){err(el,'اكتب رقم موبايل مصري صحيح مثل 01xxxxxxxxx');ok=false}});if(form.elements.studentPhone.value&&form.elements.parentPhone.value&&form.elements.studentPhone.value===form.elements.parentPhone.value){err(form.elements.parentPhone,'رقم ولي الأمر يجب أن يكون مختلفًا عن رقم الطالب');ok=false}}return ok}
  function d(){return Object.fromEntries(new FormData(form).entries())}
  function review(){const x=d(),g=groups.find(y=>y.id===Number(x.group));$('#reviewBox').innerHTML=[['المرحلة',stageObj()?.name],['الصف',gradeObj()?.name],['المادة',subjectObj()?.name],['المدرس',teachers.find(t=>t.id===Number(x.teacher))?.name||g?.teacher_name||'يحدد بعد التواصل'],['المجموعة',g?`${g.code} • ${[g.days,g.time].filter(Boolean).join(' • ')}${g.status==='full'?' • قائمة انتظار':''}`:'تحدد بعد التواصل'],['اسم الطالب',x.studentName],['رقم الطالب',x.studentPhone],['ولي الأمر',x.parentName],['رقم ولي الأمر',x.parentPhone],['ملاحظة',x.note||'—']].map(([a,b])=>`<div class="reviewRow"><span>${U.esc(a)}</span><strong>${U.esc(b||'—')}</strong></div>`).join('')}
  $$('.nextBtn',form).forEach(b=>b.onclick=()=>{if(!validate())return;if(current===2)review();show(current+1)});$$('.prevBtn',form).forEach(b=>b.onclick=()=>show(current-1));
  form.onsubmit=async e=>{e.preventDefault();if(!validate())return;const x=d();if(x.website)return;const g=groups.find(y=>y.id===Number(x.group));const payload={student_name:x.studentName,student_phone:x.studentPhone,parent_name:x.parentName,parent_phone:x.parentPhone,stage_id:Number(x.stage),grade_id:Number(x.grade),subject_id:Number(x.subject)||null,subject_text:subjectObj()?.name||'',teacher_id:Number(x.teacher)||g?.teacher_id||null,group_id:Number(x.group)||null,student_note:x.note||'',privacy_version:'2.0',source:{utm_source:q.get('utm_source')||'',utm_medium:q.get('utm_medium')||'',utm_campaign:q.get('utm_campaign')||'',referrer:document.referrer||'',page:location.pathname}};try{form.classList.add('is-busy');const r=await A.post('/api/public/register',payload);last=r.registration;$('#successId').textContent=last.request_code;const msg=$('#successMessage');if(msg)msg.textContent=(r.waiting?`المجموعة مكتملة وتم وضعك في قائمة الانتظار رقم ${r.waitlist_position}. `:'تم حفظ الطلب في قاعدة بيانات السنتر بنجاح. ')+`بعد اعتماد التسجيل من الإدارة سيصدر رقم متابعة خاص ويُرسل إلى ولي الأمر.`;show(4)}catch(e){banner.textContent=e.message;banner.classList.add('show')}finally{form.classList.remove('is-busy')}};
  $('#sendWa')?.addEventListener('click',e=>{if(!last){e.preventDefault();return}const m=[`طلب تسجيل - سنتر سعيد`,`رقم الطلب: ${last.request_code}`,`الطالب: ${last.student_name}`,`المادة: ${last.subject_text}`,`الحالة: ${last.status==='waiting'?'قائمة انتظار':'تم إنشاء الطلب'}`,`رقم ولي الأمر: ${last.parent_phone}`].join('\n');e.currentTarget.href=`https://wa.me/${window.SAEED_CONFIG.phoneIntl}?text=${encodeURIComponent(m)}`});
  $('#copyId')?.addEventListener('click',async()=>{if(!last)return;await navigator.clipboard.writeText(last.request_code);$('#copyId').textContent='تم النسخ ✓'});
  (async()=>{try{const [c,g,t]=await Promise.all([A.get('/api/public/catalog'),A.get('/api/public/groups'),A.get('/api/public/teachers')]);catalog=c.stages;groups=g.groups;teachers=t.teachers;set(stage,catalog.map(x=>({value:x.id,label:x.name})),'اختر المرحلة');if(q.get('stage_id')){stage.value=q.get('stage_id');syncGrades();if(q.get('grade_id')){grade.value=q.get('grade_id');syncSubjects()}}if(q.get('group')){const selected=groups.find(x=>x.id===Number(q.get('group')));if(selected){stage.value=selected.stage_id;syncGrades();grade.value=selected.grade_id;syncSubjects();const sub=gradeObj()?.subjects.find(x=>x.name===selected.subject_text);if(sub){subject.value=sub.id;syncPeople()}group.value=selected.id}}show(0)}catch(e){form.innerHTML=`<div class="errorBanner show">تعذر تحميل بيانات التسجيل: ${U.esc(e.message)}</div>`}})();
})();
