const zlib=require('zlib');
const crcTable=(()=>{const t=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();
function crc32(buf){let c=0xffffffff;for(const b of buf)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[m]))}
function col(n){let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}
function makeXlsx(rows, sheetName='Sheet1'){
  const headers=rows.length?Object.keys(rows[0]):[];
  const grid=[headers,...rows.map(r=>headers.map(h=>r[h]??''))];
  const sheet=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${grid.map((r,ri)=>`<row r="${ri+1}">${r.map((v,ci)=>{const ref=`${col(ci+1)}${ri+1}`;if(typeof v==='number'&&Number.isFinite(v))return `<c r="${ref}"><v>${v}</v></c>`;return `<c r="${ref}" t="inlineStr"><is><t>${esc(v)}</t></is></c>`}).join('')}</row>`).join('')}</sheetData></worksheet>`;
  const entries={
    '[Content_Types].xml':`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`,
    '_rels/.rels':`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`,
    'xl/workbook.xml':`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${esc(sheetName).slice(0,31)}" sheetId="1" r:id="rId1"/></sheets></workbook>`,
    'xl/_rels/workbook.xml.rels':`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`,
    'xl/worksheets/sheet1.xml':sheet
  };
  return zipStore(entries)
}
function zipStore(entries){let offset=0;const locals=[],centrals=[];for(const [name,data] of Object.entries(entries)){const n=Buffer.from(name),b=Buffer.from(data),crc=crc32(b);const lh=Buffer.alloc(30);lh.writeUInt32LE(0x04034b50,0);lh.writeUInt16LE(20,4);lh.writeUInt16LE(0,6);lh.writeUInt16LE(0,8);lh.writeUInt16LE(0,10);lh.writeUInt16LE(0,12);lh.writeUInt32LE(crc,14);lh.writeUInt32LE(b.length,18);lh.writeUInt32LE(b.length,22);lh.writeUInt16LE(n.length,26);lh.writeUInt16LE(0,28);locals.push(lh,n,b);const ch=Buffer.alloc(46);ch.writeUInt32LE(0x02014b50,0);ch.writeUInt16LE(20,4);ch.writeUInt16LE(20,6);ch.writeUInt16LE(0,8);ch.writeUInt16LE(0,10);ch.writeUInt16LE(0,12);ch.writeUInt16LE(0,14);ch.writeUInt32LE(crc,16);ch.writeUInt32LE(b.length,20);ch.writeUInt32LE(b.length,24);ch.writeUInt16LE(n.length,28);ch.writeUInt16LE(0,30);ch.writeUInt16LE(0,32);ch.writeUInt16LE(0,34);ch.writeUInt16LE(0,36);ch.writeUInt32LE(0,38);ch.writeUInt32LE(offset,42);centrals.push(ch,n);offset+=lh.length+n.length+b.length}const central=Buffer.concat(centrals),local=Buffer.concat(locals),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(0,4);end.writeUInt16LE(0,6);const count=Object.keys(entries).length;end.writeUInt16LE(count,8);end.writeUInt16LE(count,10);end.writeUInt32LE(central.length,12);end.writeUInt32LE(local.length,16);end.writeUInt16LE(0,20);return Buffer.concat([local,central,end])}
function unzipEntries(buf){const out={};let pos=buf.lastIndexOf(Buffer.from([0x50,0x4b,0x05,0x06]));if(pos<0)throw new Error('Invalid XLSX');const centralOffset=buf.readUInt32LE(pos+16),count=buf.readUInt16LE(pos+10);let p=centralOffset;for(let i=0;i<count;i++){if(buf.readUInt32LE(p)!==0x02014b50)throw new Error('Invalid ZIP directory');const method=buf.readUInt16LE(p+10),comp=buf.readUInt32LE(p+20),nameLen=buf.readUInt16LE(p+28),extraLen=buf.readUInt16LE(p+30),commentLen=buf.readUInt16LE(p+32),localOffset=buf.readUInt32LE(p+42),name=buf.slice(p+46,p+46+nameLen).toString();const lp=localOffset,lname=buf.readUInt16LE(lp+26),lextra=buf.readUInt16LE(lp+28),start=lp+30+lname+lextra,raw=buf.slice(start,start+comp);out[name]=method===0?raw:method===8?zlib.inflateRawSync(raw):Buffer.alloc(0);p+=46+nameLen+extraLen+commentLen}return out}
function unesc(s){return String(s||'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&')}
function strip(s){return unesc(String(s||'').replace(/<[^>]*>/g,''))}
function parseXlsx(buf){const e=unzipEntries(buf),sheet=(e['xl/worksheets/sheet1.xml']||Object.entries(e).find(([k])=>k.startsWith('xl/worksheets/sheet'))?.[1]);if(!sheet)throw new Error('Worksheet not found');let shared=[];if(e['xl/sharedStrings.xml']){const ss=e['xl/sharedStrings.xml'].toString();shared=[...ss.matchAll(/<si[^>]*>([\s\S]*?)<\/si>/g)].map(m=>[...m[1].matchAll(/<t[^>]*>([\s\S]*?)<\/t>/g)].map(x=>unesc(x[1])).join(''))}const xml=sheet.toString(),rows=[];for(const rm of xml.matchAll(/<row[^>]*>([\s\S]*?)<\/row>/g)){const arr=[];for(const cm of rm[1].matchAll(/<c([^>]*)>([\s\S]*?)<\/c>/g)){const attrs=cm[1],body=cm[2],ref=(attrs.match(/\br="([A-Z]+)\d+"/)||[])[1]||'',idx=ref?lettersToIndex(ref):arr.length;let v='';if(/\bt="s"/.test(attrs)){const n=Number((body.match(/<v>([\s\S]*?)<\/v>/)||[])[1]);v=shared[n]??''}else if(/\bt="inlineStr"/.test(attrs)){v=[...body.matchAll(/<t[^>]*>([\s\S]*?)<\/t>/g)].map(x=>unesc(x[1])).join('')}else v=strip((body.match(/<v>([\s\S]*?)<\/v>/)||[])[1]||'');arr[idx]=v}rows.push(arr)}const headers=(rows.shift()||[]).map(x=>String(x||'').trim());return rows.filter(r=>r.some(x=>String(x||'').trim())).map(r=>Object.fromEntries(headers.map((h,i)=>[h||`col${i+1}`,r[i]??''])))}
function lettersToIndex(s){let n=0;for(const ch of s)n=n*26+(ch.charCodeAt(0)-64);return n-1}
module.exports={makeXlsx,parseXlsx};
