const fs=require('fs'),path=require('path'),os=require('os'),cp=require('child_process');
const root=path.resolve(__dirname,'..');
const must=['server.js','db.js','xlsx-lite.js','public/api.js','public/components.js','public/app.js','public/register.js','public/portal.js','public/admin.js','public/pdf-export.js','public/style.css','public/index.html','public/admin.html','public/register.html','public/portal.html','public/schedule.html','public/teachers.html','public/gallery.html','public/results.html'];
let errors=[];
for(const f of must)if(!fs.existsSync(path.join(root,f)))errors.push(`Missing ${f}`);
for(const f of ['server.js','db.js','xlsx-lite.js','env-loader.js','start-local.js']){const r=cp.spawnSync(process.execPath,['--check',path.join(root,f)],{encoding:'utf8'});if(r.status!==0)errors.push(`${f}: ${r.stderr.trim()}`)}
for(const f of fs.readdirSync(path.join(root,'public')).filter(x=>x.endsWith('.js'))){const r=cp.spawnSync(process.execPath,['--check',path.join(root,'public',f)],{encoding:'utf8'});if(r.status!==0)errors.push(`public/${f}: ${r.stderr.trim()}`)}
for(const f of fs.readdirSync(path.join(root,'scripts')).filter(x=>x.endsWith('.js'))){if(f==='self-check.js')continue;const r=cp.spawnSync(process.execPath,['--check',path.join(root,'scripts',f)],{encoding:'utf8'});if(r.status!==0)errors.push(`${f}: ${r.stderr.trim()}`)}
for(const file of fs.readdirSync(path.join(root,'public')).filter(x=>x.endsWith('.html'))){const text=fs.readFileSync(path.join(root,'public',file),'utf8');for(const m of text.matchAll(/(?:href|src)=["']([^"']+)["']/g)){let u=m[1];if(!u||u.startsWith('#')||u.startsWith('http:')||u.startsWith('https:')||u.startsWith('tel:')||u.startsWith('mailto:')||u.startsWith('data:')||u.startsWith('/api/')||u.startsWith('/uploads/'))continue;u=u.split(/[?#]/)[0].replace(/^\//,'');if(u&&!fs.existsSync(path.join(root,'public',u)))errors.push(`${file}: broken local reference ${u}`)}}
const temp=path.join(os.tmpdir(),`saeed-selfcheck-${process.pid}.db`);const dbtest=cp.spawnSync(process.execPath,['-e',`process.env.DB_PATH=${JSON.stringify(temp)};const d=require(${JSON.stringify(path.join(root,'db.js'))});d.init();const names=new Set(d.all('PRAGMA table_list').map(x=>x.name));for(const t of ['student_enrollments','message_reads','message_recipients','notification_logs'])if(!names.has(t))throw new Error('Missing '+t);const cols=d.all('PRAGMA table_info(registrations)').map(x=>x.name);if(!cols.includes('tracking_code'))throw new Error('Missing tracking_code');const gc=d.all('PRAGMA table_info(student_grades)').map(x=>x.name);if(!gc.includes('image_url')||!gc.includes('enrollment_id'))throw new Error('Missing exam image/enrollment fields');console.log('db-v4-ok')`],{encoding:'utf8'});if(dbtest.status!==0)errors.push('DB init/migration: '+dbtest.stderr.trim());try{for(const x of [temp,temp+'-wal',temp+'-shm'])fs.rmSync(x,{force:true})}catch{}
try{const {makeXlsx,parseXlsx}=require(path.join(root,'xlsx-lite.js'));const b=makeXlsx([{'اسم الطالب':'اختبار','المبلغ':123}],'Test'),rows=parseXlsx(b);if(rows[0]?.['اسم الطالب']!=='اختبار'||Number(rows[0]?.['المبلغ'])!==123)errors.push('XLSX round-trip failed')}catch(e){errors.push('XLSX: '+e.message)}
if(errors.length){console.error('SELF-CHECK FAILED');errors.forEach(e=>console.error('- '+e));process.exit(1)}
console.log('SELF-CHECK PASSED');console.log('Files, JavaScript syntax, local references, SQLite v4 parent-portal schema/migrations and XLSX round-trip are valid.');
